views.py
# views.py
from flask import Blueprint, render_template, request
from flask_login import login_user, logout_user, login_required, current_user
# Crea un Blueprint llamado 'views'
views_bp = Blueprint('views', __name__)

@views_bp.route('/')
def index():
    return render_template('index.html')

@views_bp.route('/shop')
def shop():
    return render_template('shop.html')

@views_bp.route('/contact')
def contact():
    return render_template('contact.html')

@views_bp.route('/comprar')
def sell():
    return render_template('comprar.html')

@views_bp.route('/carrito')
def carrito():
    return render_template('carrito.html')

@views_bp.route('/register')
def register():
    return render_template('register.html')

@views_bp.route('/login')
def login():
    return render_template('login.html')

@views_bp.route('/detallesproducto')
def detallesproducto():
    product_id = request.args.get('id')
    return render_template('detallesproducto.html', product_id=product_id)

@views_bp.route('/editarproducto')
def editarproducto():
    product_id = request.args.get('id')
    return render_template('editarproducto.html', product_id=product_id)

@views_bp.route('/registroproducto')
@login_required
def registroproducto():
    return render_template('registroproducto.html')

@views_bp.route('/misproductos')
@login_required
def misproductos():
    return render_template('misproductos.html')

@views_bp.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <!-- titulo e icono-->
    <title>Oceano Fresco</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='assets/images/iconochallwa.ico') }}">
    <!-- titulo e icono-->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/fontawesome.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/templatemo-lugx-gaming.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/owl.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/animate.css') }}">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
</head>

<body>
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->

    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="/" class="logo">
                            <img src="{{ url_for('static', filename='assets/images/oceanoLogo.png') }}" alt=""
                                style="width: 220px;">
                            <!-- Colocar el logo de challwacom -->
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="{{ url_for('views.index') }}" class="active">Inicio</a></li>

                            {% if current_user.is_authenticated %}
                            <li><a href="{{ url_for('views.misproductos') }}">Mis Productos</a></li>
                            <li><a href="{{ url_for('views.registroproducto') }}">Añadir Producto</a></li>
                            <li><a href="{{ url_for('views.profile') }}">Mi Perfil</a></li>
                            <li><a href="#" id="logout-button">Cerrar sesión</a></li>
                            <!-- Agrega un ID al botón de cerrar sesión -->
                            {% else %}
                            <li><a href="{{ url_for('views.shop') }}">Tienda</a></li>
                            <li><a href="{{ url_for('views.carrito') }}">Carrito</a></li>
                            <li><a href="{{ url_for('views.register') }}">Regístrate</a></li>
                            <li><a href="{{ url_for('views.login') }}">Inicia sesión</a></li>
                            {% endif %}
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>


    <div class="content">
        {% block content %}{% endblock %}
        <!-- El bloque 'content' se rellenará en las páginas específicas -->
    </div>

    <footer>
        <div class="container">
            <div class="col-lg-12">
                <p>Copyright © 2024 OceanoFresco. &nbsp;&nbsp;</p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/isotope.min.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/owl-carousel.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/counter.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/custom.js') }}"></script>
    <!-- scripts propios -->
    <script src="{{ url_for('static', filename='js/basehtml.js')}}"></script>
</body>

</html>

templates/carrito.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}

<head>
  <!-- css propios -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/carrito.css') }}">
</head>

<div class="page-heading header-text">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>Tu carrito</h3>
        <span class="breadcrumb"><a href="#">Home</a> > Mi carrito</span>
      </div>
    </div>
  </div>
</div>

<div id="alert" class="alert alert-success mt-3" style="display: none;"></div>

<div class="carrrito">
  <div class="cart-container">
    <div id="cart-items"></div>
    <button id="checkout-button">Proceder a Compra</button>
    <a href="/shop">
      <button id="checkout-button">Volver a Tienda</button>
    </a>
  </div>
</div>



<!-- scripts propios-->
<script src="{{ url_for('static', filename='js/carrito.js') }}"></script>



{% endblock %}

templates/comprar.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}

<!-- estilos propios -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/comprar.css') }}">

<div class="page-heading header-text">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>Comprar</h3>
        <span class="breadcrumb"><a href="#">Home</a> > Comprar</span>
      </div>
    </div>
  </div>
</div>




<div class="comprar-container">
  <div class="comprar-left">
    <h4>Detalles del Comprador</h4>
    <form id="comprador-form">
      <div class="form-group">
        <label for="comprador-nombre">Nombre:</label>
        <input type="text" id="comprador-nombre" required>
      </div>
      <div class="form-group">
        <label for="comprador-apellido">Apellido:</label>
        <input type="text" id="comprador-apellido" required>
      </div>
      <div class="form-group">
        <label for="comprador-direccion">Dirección de Envío:</label>
        <input type="text" id="comprador-direccion" required>
      </div>
      <div class="form-group">
        <label for="comprador-dni">DNI:</label>
        <input type="number" id="comprador-dni" required min="8">
      </div>
    </form>
  </div>
  <div class="comprar-right">
    <h4>Resumen del Pedido</h4>
    <div class="resumen-boleta">
      <ul id="productos-carrito"></ul>
      <p><strong>Delivery:</strong> S/. 6.00</p>
      <p><strong>Total:</strong> S/. <span id="total-precio"></span></p>
    </div>
    <button id="comprar-button" disabled>Solicitar compra</button>
  </div>
</div>

<!-- scripts propips -->
<script src="{{ url_for('static', filename='js/comprar.js') }}"></script>

{% endblock %}

templates/contact.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}

<div class="page-heading header-text">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>Contact Us</h3>
        <span class="breadcrumb"><a href="#">Home</a> > Contact Us</span>
      </div>
    </div>
  </div>
</div>

<div class="contact-page section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 align-self-center">
        <div class="left-text">
          <div class="section-heading">
            <h6>Contact Us</h6>
            <h2>Say Hello!</h2>
          </div>
          <p>LUGX Gaming Template is based on the latest Bootstrap 5 CSS framework. This template is provided by
            TemplateMo and it is suitable for your gaming shop ecommerce websites. Feel free to use this for any
            purpose. Thank you.</p>
          <ul>
            <li><span>Address</span> Sunny Isles Beach, FL 33160, United States</li>
            <li><span>Phone</span> +123 456 7890</li>
            <li><span>Email</span> lugx@contact.com</li>
          </ul>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="right-content">
          <div class="row">
            <div class="col-lg-12">
              <div id="map">
                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth"
                  width="100%" height="325px" frameborder="0" style="border:0; border-radius: 23px;"
                  allowfullscreen=""></iframe>
              </div>
            </div>
            <div class="col-lg-12">
              <form id="contact-form" action="" method="post">
                <div class="row">
                  <div class="col-lg-6">
                    <fieldset>
                      <input type="name" name="name" id="name" placeholder="Your Name..." autocomplete="on" required>
                    </fieldset>
                  </div>
                  <div class="col-lg-6">
                    <fieldset>
                      <input type="surname" name="surname" id="surname" placeholder="Your Surname..." autocomplete="on"
                        required>
                    </fieldset>
                  </div>
                  <div class="col-lg-6">
                    <fieldset>
                      <input type="text" name="email" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your E-mail..."
                        required="">
                    </fieldset>
                  </div>
                  <div class="col-lg-6">
                    <fieldset>
                      <input type="subject" name="subject" id="subject" placeholder="Subject..." autocomplete="on">
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <textarea name="message" id="message" placeholder="Your Message"></textarea>
                    </fieldset>
                  </div>
                  <div class="col-lg-12">
                    <fieldset>
                      <button type="submit" id="form-submit" class="orange-button">Send Message Now</button>
                    </fieldset>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/detallesproducto.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}

<head>

  <style>
    /* Alert styles */
    #alert {
      text-align: center;
      padding: 10px;
      border-radius: 4px;
    }

    .alert-success {
      background-color: #d4edda;
      color: #155724;
      border: 1px solid #c3e6cb;
    }

    .alert-danger {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }

    .alert-again {
      background-color: #fff481;
      color: rgb(180, 159, 40);
      border: 1px solid gold;
    }
  </style>
</head>

<div class="page-heading header-text">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 id="product-name"></h3>
        <span class="breadcrumb">Home</a> > Tienda</a> > Comprar</span>
      </div>
    </div>
  </div>
</div>

<!-- Inicio Información del producto -->

<div class="single-product section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="left-image">
          <img id="product-image" src="" alt="">
        </div>
      </div>
      <div class="col-lg-6 align-self-center">
        <h1 id="product-name2"></h1>
        <span class="price"><em id="old-price"></em> <span id="product-price"></span><span style="color: gray;"> - por
            docena</span></span>
        <p id="product-description"></p>
        <form id="qty" action="#">
          <input type="number" class="form-control" id="quantity" aria-describedby="quantity" placeholder="1" value="1"
            min="1">
          <button type="button" class="buy-button" id="add-to-cart-button">AGREGAR AL CARRITO</button>
          <button type="button" class="buy-button" style="margin-bottom: 10px;">
            <a href="/carrito">
              <img src="{{ url_for('static', filename='assets/images/carrito.png') }}" alt="Carrito">
            </a>
          </button>
        </form>
        <ul>
          <li style="display: none"><span>PRODUCTO ID:</span> <span id="product-id"></span></li>
          <li><span>Categoria:</span> <span id="product-category"></span></li>
          <li><span>Stock:</span> <span id="product-stock"></span></li>
        </ul>
      </div>
      <div id="alert" class="alert alert-success mt-3" style="display: none;"></div>
    </div>
  </div>
</div>


<!-- Fin Información del producto -->

<!-- javascript propios -->
<script src="{{ url_for('static', filename='js/detallesproducto.js') }}"></script>

{% endblock %}

templates/editarproducto.html
{% extends "base.html" %}

{% block content %}

<head>

  <style>
    /* Alert styles */
    /* Alert styles */
    #alert {
      text-align: center;
      padding: 10px;
      border-radius: 4px;
      margin-top: 10px;
    }

    .alert-success {
      background-color: #d4edda;
      color: #155724;
      border: 1px solid #c3e6cb;
    }

    .alert-danger {
      background-color: #f8d7da;
      color: #721c24;
      border: 1px solid #f5c6cb;
    }

    .alert-again {
      background-color: #fff481;
      color: rgb(180, 159, 40);
      border: 1px solid gold;
    }

    .form-group {
      margin-bottom: 1.5rem;
      display: flex;
      flex-direction: column;
    }

    .form-group label {
      margin-bottom: 0.5rem;
      font-weight: bold;
    }

    .form-group input,
    .form-group textarea,
    .form-group select {
      width: 100%;
      padding: 0.5rem;
      border: 1px solid #ccc;
      border-radius: 4px;
    }

    .btn-primary {
      background-color: #007bff;
      border: none;
      padding: 10px 20px;
      color: white;
      border-radius: 4px;
      cursor: pointer;
    }

    .btn-primary:hover {
      background-color: #0056b3;
    }

    .stock-controls {
      display: flex;
      align-items: center;
      margin-bottom: 1.5rem;
      gap: 10px;
      /* Add gap for spacing */
    }

    .stock-controls button {
      background-color: #007bff;
      border: none;
      padding: 10px;
      color: white;
      border-radius: 4px;
      cursor: pointer;
    }

    .stock-controls button:hover {
      background-color: #0056b3;
    }

    .stock-controls input {
      width: 50px;
      text-align: center;
    }

    @media (max-width: 768px) {
      .stock-controls {
        flex-direction: column;
        /* Stack vertically on small screens */
      }

      .stock-controls button {
        width: 100%;
        margin-bottom: 5px;
      }

      .stock-controls input {
        width: 100%;
      }

      .btn-primary {
        width: 100%;
        /* Full width button on small screens */
      }
    }
  </style>
</head>

<div class="page-heading header-text">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 id="product-name"></h3>
        <span class="breadcrumb">Home > Mis Productos > Editar</span>
      </div>
    </div>
  </div>
</div>

<!-- Inicio Edición del producto -->
<div class="single-product section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="left-image">
          <img id="product-image" src="" alt="">
        </div>
      </div>
      <div class="col-lg-6 align-self-center">
        <h4 id="product-name"></h4>
        <form id="edit-product-form" enctype="multipart/form-data">
          <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" class="form-control" required>
          </div>
          <div class="form-group">
            <label for="descripcion">Descripción:</label>
            <textarea id="descripcion" name="descripcion" class="form-control" required></textarea>
          </div>
          <div class="form-group">
            <label for="precio">Precio:</label>
            <input type="number" id="precio" name="precio" class="form-control" step="0.01" required>
          </div>
          <div class="form-group">
            <label for="categoria">Categoría:</label>
            <select name="categoria" id="categoria" class="form-control" required>
              <option value="pescado">Pescado</option>
              <option value="marisco">Marisco</option>
            </select>
          </div>
          <div class="form-group">
            <label for="stock">Stock:</label>
            <div class="d-flex align-items-center">
              <button type="button" class="btn btn-secondary" id="decrease-stock">-</button>
              <input type="number" id="stock" name="stock" class="form-control mx-2 text-center" readonly required>
              <button type="button" class="btn btn-secondary" id="increase-stock">+</button>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
        <div id="alert" class="alert mt-3" style="display: none;"></div>
      </div>
    </div>
  </div>
</div>
<!-- Fin Edición del producto -->

<script src="{{ url_for('static', filename='js/editarproducto.js') }}"></script>

{% endblock %}

templates/index.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}


<head>
  <!-- css propios -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
</head>

<div class="main-banner">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 align-self-center">
        <div class="caption header-text">
          <h1 style="color: white;">Bienvenidos a Oceano Fresco</h1>
          <h2>LA PRIMERA TIENDA VIRTUAL DE PESCADOS FRESCOS!</h2>
          <p>¡Descubre lo mejor del mar con Oceano Fresco! Apoya a los pescadores artesanales y disfruta de
            productos
            Frescos y sostenibles directamente del océano. ¡Bienvenido a bordo!</p>
          <div class="search-input">
            <form id="search" action="/shop">
              <input type="text" placeholder="¿Deseas comprar?" id='searchText' name="searchKeyword" onkeypress="handle"
                readonly />
              <button role="button">Tienda AQUÍ</button>
            </form>
          </div>
          <div class="search-input">
            <form id="search" action="/registroproducto">
              <input type="text" placeholder="¿Eres pescador?" id='searchText' name="searchKeyword" onkeypress="handle"
                readonly />
              <button role="button">Publica AQUÍ</button>
            </form>
          </div>
        </div>
      </div>
      <div class="col-lg-4 offset-lg-2">
        <div class="right-image">
          <img src="{{ url_for('static', filename='assets/images/banner-image.png') }}" alt="">
        </div>
      </div>
    </div>
  </div>
</div>

<div class="features">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <a href="#">
          <div class="item">
            <div class="image">
              <img src="{{ url_for('static', filename='assets/images/fish.png') }}" alt="" style="max-width: 44px;">
            </div>
            <h4>Peces de calidad</h4>
          </div>
        </a>
      </div>
      <div class="col-lg-3 col-md-6">
        <a href="#">
          <div class="item">
            <div class="image">
              <img src="{{ url_for('static', filename='assets/images/fishing-rod.png') }}" alt=""
                style="max-width: 44px;">
            </div>
            <h4>Pesca sostenible</h4>
          </div>
        </a>
      </div>
      <div class="col-lg-3 col-md-6">
        <a href="#">
          <div class="item">
            <div class="image">
              <img src="{{ url_for('static', filename='assets/images/sailboat.png') }}" alt="" style="max-width: 44px;">
            </div>
            <h4>Embarcaciones aptas</h4>
          </div>
        </a>
      </div>
      <div class="col-lg-3 col-md-6">
        <a href="#">
          <div class="item">
            <div class="image">
              <img src="{{ url_for('static', filename='assets/images/users.png') }}" alt="" style="max-width: 44px;">
            </div>
            <h4>Conectando con la comunidad</h4>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<!-- Inicio de los videos -->
<div class="video-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="video-container">
          <iframe width="340" height="630" src="https://www.youtube.com/embed/m65GzBKsHiA?si=pG0WE3TZPhrOxprl"
            title="YouTube video player" frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
          <p class="video-description">Este video te muestra cómo utilizar nuestra página como comprador.</p>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="video-container">
          <iframe width="340" height="630" src="https://www.youtube.com/embed/ePJ29ycSw8o?si=aDIEmwvfMqYEjZDV"
            title="YouTube video player" frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
          <p class="video-description">Este video te enseña cómo manejar nuestra página eficientemente.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Fin de los videos -->


<div class="section cta">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">
        <div class="shop">
          <div class="row">
            <div class="col-lg-12">
              <div class="section-heading">
                <h6>Nuestra tienda</h6>
                <h2>¡Haga su pedido anticipado, compre y obtenga los mejores <em>precios</em> para
                  usted!</h2>
              </div>
              <p>Pescadores artesanales confiables más cerca de ti</p>
              <div class="main-button">
                <a href="/shop">Explorar la tienda</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-2 align-self-end">
        <div class="subscribe">
          <div class="row">
            <div class="col-lg-12">
              <div class="section-heading">
                <h6>Boletín informativo</h6>
                <h2>Accede a mucha más información acerca de los peces de la costa peruana
                  <em>Subscribete </em>al
                  Boletin informativo!
                </h2>
              </div>
              <div class="search-input">
                <form id="subscribe" action="/agregar_correo" method="post">
                  <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                    placeholder="Tu correo..." name="correo">
                  <button type="submit" value="Agregar Correo">Subscrirse ahora</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.getElementById('subscribe').onsubmit = function (event) {
    event.preventDefault(); // Previene el comportamiento por defecto del formulario

    // Verifica que el correo tenga "@" y ".com"
    var correo = document.getElementById('exampleInputEmail1').value;
    if (correo.includes('@') && correo.includes('.com')) {
      // Crea un objeto FormData con los datos del formulario
      var formData = new FormData(event.target);

      // Realiza la petición POST al servidor
      fetch('/agregar_correo', {
        method: 'POST',
        body: formData
      })
        .then(response => response.json())
        .then(data => {
          alert(data.mensaje); // Muestra un alerta con el mensaje del servidor
          window.location.href = '/'; // Redirecciona a la página de inicio
        })
        .catch(error => {
          console.error('Error:', error);
        });
    } else {
      alert('Por favor, introduce un correo electrónico válido.');
    }
  };


</script>



{% endblock %}

templates/login.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}


<head>
    <!-- css propios -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
</head>


<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Inicio de Sesión</h3>
                <span class="breadcrumb"><a href="#">Home</a> > Inicia Sesion</span>
            </div>
        </div>
    </div>
</div>


<!-- formulario inicio -->
<div class="login-form section">
    <div class="container">
        <form id="login" method="post">
            <label for="email">Correo Electrónico:</label>
            <input type="email" name="email" id="email" placeholder="correo electrónico" required>

            <label for="password">Contraseña:</label>
            <input type="password" name="password" id="password" placeholder="contraseña" required>

            <div id="error-message" style="display: none; color: red; margin-top: 10px; border: 1px solid red; border-radius: 5px; padding: 10px;"></div>

            <button type="submit" id="form-submit" class="main-button" disabled>Inicia sesion</button>
        </form>
    </div>
</div>
<!-- formulario fin -->


<!-- javascript propios -->
<script src="{{ url_for('static', filename='js/login.js') }}"></script>

{% endblock %}

templates/misproductos.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}

<head>
  <!-- css propios -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/misproductos.css') }}">
</head>


<div class="page-heading header-text">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>Mis Productos</h3>
        <span class="breadcrumb"><a href="#">Home</a> > Mis Productos</span>
      </div>
    </div>
  </div>
</div>

<div class="containermisproductos">
  <div class="row" id="misproductos-container">
    <!-- Aquí se cargarán los productos del usuario logueado dinámicamente -->
  </div>
  <ul class="pagination">
    <!-- Aquí se agregarán los enlaces de paginación dinámicamente -->
  </ul>
</div>

<!-- Modal de confirmación -->
<div id="deleteModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <p>¿Estás seguro de que deseas eliminar este producto?</p>
    <button id="confirmDelete">Eliminar</button>
    <button id="cancelDelete">Cancelar</button>
  </div>
</div>

<!-- javascript propios -->
<script src="{{ url_for('static', filename='js/misproductos.js') }}"></script>

{% endblock %}

templates/register.html
<!-- index.html -->
{% extends "base.html" %}

{% block content %}

<head>
    <!-- css propios -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
</head>


<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Registro de Pescador</h3>
                <span class="breadcrumb"><a href="#">Home</a> > Registrate</span>
            </div>
        </div>
    </div>
</div>

<!-- formulario inicio -->

<div class="register-form section">
    <div class="container">
        <form id="register" method="post">
            <label for="nombre">Nombres:</label>
            <input type="text" name="nombre" id="nombre" placeholder="nombres" required>

            <label for="apellido">Apellidos:</label>
            <input type="text" name="apellido" id="apellido" placeholder="apellidos" required>

            <label for="email">Correo Electrónico:</label>
            <input type="email" name="email" id="email" placeholder="correo electrónico" required>

            <label for="password">Contraseña:</label>
            <input type="password" name="password" id="password" placeholder="contraseña" required>

            <label for="role">¿Qué planeas hacer en la página?</label>
            <select name="role" id="role" required>
                <option value="vendedor">Quiero vender</option>
            </select>

            <!-- Contenedor para el campo de teléfono -->
            <div id="phone-container">
                <label for="telefono">Número de Teléfono:</label>
                <input type="text" name="telefono" id="telefono" placeholder="número de teléfono">
            </div>

            <button type="submit" id="form-submit" class="main-button" disabled>Registrate e inicia sesion</button>
        </form>
    </div>
</div>

<!-- formulario fin -->

<!-- javascript propios -->
<script src="{{ url_for('static', filename='js/register.js') }}"></script>


{% endblock %}